### ISSUE TITLE
Express-like debug logging for @gasket/plugin-engine

### ISSUE THREAD

**Issue by indexzero** [godaddy/gasket#151]
If one runs the following:

```
npm i -g @gasket/cli
gasket create myapp -p @gasket/preset-nextjs
cd myapp
npx gasket build
DEBUG=express* npx gasket local
```

We quickly see the express debug output: 

```
  express:application set "x-powered-by" to true +0ms
  express:application set "etag" to 'weak' +1ms
  express:application set "etag fn" to [Function: generateETag] +0ms
  express:application set "env" to 'development' +1ms
  express:application set "query parser" to 'extended' +0ms
  express:application set "query parser fn" to [Function: parseExtendedQueryString] +0ms
  express:application set "subdomain offset" to 2 +0ms
  express:application set "trust proxy" to false +0ms
  express:application set "trust proxy fn" to [Function: trustNone] +1ms
  express:application booting in development mode +0ms
  express:application set "view" to [Function: View] +0ms
  express:application set "views" to './myapp/views' +0ms
  express:application set "jsonp callback name" to 'callback' +0ms
  express:router use '/' query +0ms
  express:router:layer new '/' +0ms
  express:router use '/' expressInit +1ms
  express:router:layer new '/' +0ms
  express:router use '/' cookieParser +0ms
  express:router:layer new '/' +0ms
  express:router use '/' compression +0ms
  express:router:layer new '/' +0ms
  express:router use '/' middleware +5ms
  express:router:layer new '/' +1ms
  express:application set "buildId" to 'A-9cIUPb32ud1LBi1mROp' +40ms
  express:router:route new '*' +2ms
  express:router:layer new '*' +0ms
  // ...
  // ... etc
  // ...
```

Today we do a good job of documenting the possible graph of Hooks, and Lifecycles that will be executed for a given Command:

![Screen Shot 2020-02-20 at 1 54 26 AM](https://user-images.githubusercontent.com/4624/74908530-10bf9180-5384-11ea-9467-dc3ecc47f11c.png)

However, when we consider the plugin & preset authoring experience it's not as much about understanding the entire graph of possibilities but mapping out and debugging a single walk of that graph for a given gasket app process. This can be challenging today and a full understanding of the order of operations is often based on intuition, not hard data.

I propose we add similar debug output to `@gasket/engine` so that when one runs:

```
DEBUG=gasket* npx gasket start
```

They would get the walk of the graph of all hooks when starting at `gasket/plugin-start` above and moving from left to right in the traversal order that happens at runtime.

**Comment by xirdneh** [comment]
@rxmarbles I would like to take on this issue for Hacktoberfest.

I'm trying to figure out how the debugger is initialized and used in your example so I can add something similar to `@gasket/plugin-engine`
Also, by `@gasket/plugin-engine` do you mean [this plugin](https://github.com/godaddy/gasket/tree/master/packages/gasket-engine)?

Thanks!

**Comment by rmarkins-godaddy** [comment]
> @rxmarbles I would like to take on this issue for Hacktoberfest.
> 
> I'm trying to figure out how the debugger is initialized and used in your example so I can add something similar to `@gasket/plugin-engine`
> Also, by `@gasket/plugin-engine` do you mean [this plugin](https://github.com/godaddy/gasket/tree/master/packages/gasket-engine)?
> 
> Thanks!

Yes that is the correct package that this is issue is meant for. As for how the debugger is initialized I will refer to @kinetifex or @DullReferenceException as they were the main collaborators on this project

**Comment by kinetifex** [comment]
@xirdneh correct, it would be in the `@gasket/engine` package - I edited the original comment to fix this. For the debug logging, you'd want to use [diagnostics](https://www.npmjs.com/package/diagnostics), which is also used in the `@gasket/cli` [for example](https://github.com/godaddy/gasket/blob/master/packages/gasket-cli/src/hooks/init.js#L2).
